dist: bionic

virt: lxd

group: edge

language: 
  - go
  - python

go:
  - 1.11.x
  - 1.13.x
  - master

arch:
  - amd64
  - arm64
  - arm64-graviton2
  - ppc64le

jobs:
  allow_failures:
    - go: master
  fast_finish: true
  exclude:
    - arch: arm64-graviton2
      go: 1.11.x
    - arch: arm64
      go: 1.11.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  global:
    - GO111MODULE=on

script:
  - sudo apt -y install acpid
  - sudo apt -y install alsa-base
  - sudo apt -y install amavisd-new
  - sudo apt -y install alembic
  - sudo apt -y install aide-common
  - sudo apt -y install adwaita-icon-theme
  - sudo apt -y install adium-theme-ubuntu
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
  - go test -v -race ./...
