dist: bionic

virt: lxd

group: edge

language: 
  - go
  - python

go:
  - 1.11.x
  - 1.13.x
  - master

arch:
  - amd64
  - arm64
  - arm64-graviton2
  - ppc64le

jobs:
  allow_failures:
    - go: master
  fast_finish: true
  exclude:
    - arch: arm64-graviton2
      go: 1.11.x
    - arch: arm64
      go: 1.11.x

cache:
  directories:
    - $HOME/.cache/go-build
    - $HOME/gopath/pkg/mod

env:
  global:
    - GO111MODULE=on

script:
  - pip3 install pypack coverage brotlipy pycares  cffi lazy-object-proxy pyyaml surt reppy psutil extensions pur pytest-sugar Hdrhistogram cchardet pycares future maxminddb termcolor docopt wrapt uvloop nose rsa simplejson argparse httpretty mock pynacl biopython pyvcf pycryptodome pymesos http-parser MarkupSafe
  - diff -u <(echo -n) <(gofmt -d -s .)
  - go vet ./...
  - go test -v -race ./...
